### ISSUE TITLE
Empty variable: multiple error messages

### ISSUE THREAD

**Issue by mgrunko** [millennialmedia/intellibot#172]
If there is an empty variable, IntelliBot throws multiple exceptions (about 100), so that IntelliJ stops monitoring.

To reproduce it, type a variable and simple do not write its value (screenshot [hier](http://s33.postimg.org/vha3pk37j/pic_10_06_2016_13_06_02.png))

I got the following two errors:
1) IntelliJ: `com.intellij.diagnostic.MessagePool$TooManyErrorsException: Too many IDE fatal errors. Monitoring stopped.`
2) IntelliBot:
> PsiElement(VARIABLE_DEFINITION)
> java.lang.AssertionError: PsiElement(VARIABLE_DEFINITION)
> 	at com.intellij.psi.impl.source.text.DiffLog$InsertEntry.<init>(DiffLog.java:175)
> 	at com.intellij.psi.impl.source.text.DiffLog$InsertEntry.<init>(DiffLog.java:169)
> 	at com.intellij.psi.impl.source.text.DiffLog.nodeInserted(DiffLog.java:88)
> 	at com.intellij.psi.impl.source.text.DiffLog.nodeInserted(DiffLog.java:41)
> 	at com.intellij.lang.impl.PsiBuilderImpl$ConvertFromTokensToASTBuilder.nodeInserted(PsiBuilderImpl.java:1197)

Find the full exception message [hier](https://github.com/millennialmedia/intellibot/files/308899/Exception.message.txt)

**Comment by ss12344** [comment]
I also see this.

**Comment by Elizaveta239** [comment]
Yet another report in PyCharm's issue tracker: https://youtrack.jetbrains.com/issue/PY-21859
