### ISSUE TITLE
"Keyword definition not found" for SeleniumLibrary in PyCharm

### ISSUE THREAD

**Issue by super-sqa** [millennialmedia/intellibot#191]
I tried several different things including switching interpreter and and virtual environments.
PyCharm still shows the keywords as undefined. The test runs fine. Also no autocompletion or suggestion when I start to type the keywords. 
![screen shot 2017-10-06 at 4 27 42 pm](https://user-images.githubusercontent.com/11204418/31302028-5c246910-aab3-11e7-948a-3ef58130cc0c.png)

![screen shot 2017-10-06 at 4 29 39 pm](https://user-images.githubusercontent.com/11204418/31302052-9b06f292-aab3-11e7-925c-f2423b87b3d7.png)

![screen shot 2017-10-06 at 4 30 15 pm](https://user-images.githubusercontent.com/11204418/31302057-aa45e132-aab3-11e7-9322-0dba4b27f3bb.png)

**Comment by amolagare** [comment]
I have a similar issue on Windows Pycharm. Even if I have installed Intellibot and Selenium Robot Framework as per instructions, I am not able to see the keywords highlighted.

![image](https://user-images.githubusercontent.com/32615027/31317454-043025c0-ac5f-11e7-88f9-da98275dddbe.png)

![image](https://user-images.githubusercontent.com/32615027/31317464-20c655ba-ac5f-11e7-93d3-de9f1d76de28.png)

**Comment by MbryantAE** [comment]
any solutions? or workarounds? im having the same issue

**Comment by dwaynep** [comment]
I'm having the same issue. Any resolution?

**Comment by david-kalman** [comment]
Same issue here with PyCharm 2017.2.4. No issue running the tests.
Auto-completion works fine with other libraries (AppiumLibrary, Selenium2Library)

**Comment by benzhou2014** [comment]
I am exactly same issue, I updated the PyCharm to the latest community one 2017.1.2.

**Comment by mumugoah** [comment]
I'm having the same issue, It works good before

**Comment by tmhung-nt** [comment]
The plugin does work with selenium2library version 1.8.0, but not with the latest version (seleniumLibrary version 3)

**Comment by preethiganeshamurthy** [comment]
Did you find a workaround for this issue. Even I am having same issue.

**Comment by Tajindar** [comment]
Same issue with me

**Comment by Tajindar** [comment]
Any Solution

**Comment by max-silent** [comment]
The same for me (PyCharm 2017.3.2 community edition). Reproducible with both Selenium2Library (3.0.0) and SeleniumLibrary (3.0.1). IntelliBot version: 0.10.143.381.

Is there any plans for resolving the issue?

P.S.: According to the following comment - it's not a SeleniumLibrary issue:
https://github.com/robotframework/SeleniumLibrary/issues/937#issuecomment-334410728

**Comment by bigMacGO** [comment]
hey, is any possibility it will be fixed? or any known workarounds?

**Comment by 29er** [comment]
Same here! Please assist.

**Comment by radezivanovic** [comment]
I had the same issue and I found a workaround for this.
The issue seems to be related to the new SeleniumLibrary after all, but everything still works with the legacy Selenium2Library.

You will need to install legacy library and then import it in your project for keyword definitions to be resolved:
pip install robotframework-selenium2library==1.8.0

then change in your project:
Library  SeleniumLibrary  

to:

Library  Selenium2Library  

and all of a sudden all the keywords are resolved correctly.

You can still use SeleniumLibrary to execute your tests, you just need legacy Selenium2Library import to make your life easier while writing tests.

Hope this helps.

**Comment by outcatcher** [comment]
The issue is clearly related to the fact that SeleniumLibrary 3+ is [dynamic library](https://github.com/robotframework/PythonLibCore/blob/master/README.rst). 

In case of dynamic library, keywords are resolved during test execution (you can compare S2E 1.8 and SE 3+ code). Both this [RobotFramework Support](https://plugins.jetbrains.com/plugin/7415-robot-framework-support) plugins work only with static libraries. 

If you want to use this plugin together with RF3+ with up to date keyword list, I would recommend you to use workaround (though it's dirty naughty hack), generating static library referencing keywords from dynamic one. So you can use it in your Robot resources or tests.

**Comment by bartkl** [comment]
@outcatcher I'm not familiar with the technical details of this: is it _absolutely_ impossible to resolve keywords from dynamic libraries? Or is it just very hard, requiring a complete rewrite of the plugin.

And a question relating to your workaround: would inspecting keywords (using ``Ctrl + Click``) work?

**Comment by outcatcher** [comment]
@bartkl 
There is nothing impossible 🙂 
I don't have enough experience in Java and Idea plugins, but it seems that this plugin uses internal Idea Python plugin / Pycharm resolver, so it implementing dynamic library kw resolution requires implementing new resolver.

Using static library workaround you should be able to use all standard features. At least auto-completing (*ctrl+Space*) and quick documentation (*ctrl+mouse hover*, *ctrl+Q*) is working for me. Though I need to search for exact python method in used libraries manually, but it's just an issue of my implementation.

**Comment by JoelDelumen** [comment]
The solution of radezivanovic works with me.

**Comment by bawiecek** [comment]
I have exactly the same issue while working on Mac OS. It shows the basic keywords, but not the imported one.

**Comment by JoelDelumen** [comment]
Have you tried reverting selenium2library to 1.8.0?

**Comment by bawiecek** [comment]
I am able to install this package successfully only for python2 (on Mac os
using pip).
When trying to install it either using pip3 or on virtualenv based on
python 3.6, I get VersionConflict:

➜  ~ pip3 install robotframework-selenium2library==1.8.0
Collecting robotframework-selenium2library==1.8.0
  Using cached robotframework-selenium2library-1.8.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File
"/private/var/folders/7y/qj8sb2gd01j2fl6zvmd3rvxhzty535/T/pip-build-4y5dm35j/robotframework-selenium2library/setup.py",
line 7, in <module>
        from ez_setup import use_setuptools
      File
"/private/var/folders/7y/qj8sb2gd01j2fl6zvmd3rvxhzty535/T/pip-build-4y5dm35j/robotframework-selenium2library/src/ez_setup.py",
line 106
        except pkg_resources.VersionConflict, e:
                                            ^
    SyntaxError: invalid syntax

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in
/private/var/folders/7y/qj8sb2gd01j2fl6zvmd3rvxhzty535/T/pip-build-4y5dm35j/robotframework-selenium2library/

niedz., 25 lut 2018 o 16:15 użytkownik JoelDelumen <notifications@github.com>
napisał:

> Have you tried reverting selenium2library to 1.8.0?
>

**Comment by mithunsureshqa** [comment]
I am getting an error on trying to install robotframework-selenium2library==1.8.0

MAC5PG8W:~ msuresh$ pip install robotframework-selenium2library==1.8.0
Collecting robotframework-selenium2library==1.8.0
  Downloading robotframework-selenium2library-1.8.0.tar.gz (118kB)
    100% |████████████████████████████████| 122kB 1.9MB/s
Collecting decorator>=3.3.2 (from robotframework-selenium2library==1.8.0)
  Downloading decorator-4.2.1-py2.py3-none-any.whl
Requirement already satisfied: selenium>=2.32.0 in /usr/local/lib/python2.7/site-packages (from robotframework-selenium2library==1.8.0)
Requirement already satisfied: robotframework>=2.6.0 in /usr/local/lib/python2.7/site-packages (from robotframework-selenium2library==1.8.0)
Building wheels for collected packages: robotframework-selenium2library
  Running setup.py bdist_wheel for robotframework-selenium2library ... done
  Stored in directory: /Users/<name>/Library/Caches/pip/wheels/70/59/d6/6f7d6b78b7f01f9284dcfa5dce0229ebcc7e7bb617b31153e9
Successfully built robotframework-selenium2library
Installing collected packages: decorator, robotframework-selenium2library
  Found existing installation: robotframework-selenium2library 3.0.0
    Uninstalling robotframework-selenium2library-3.0.0:
Exception:
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/site-packages/pip/basecommand.py", line 215, in main
    status = self.run(options, args)
  File "/usr/local/lib/python2.7/site-packages/pip/commands/install.py", line 342, in run
    prefix=options.prefix_path,
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_set.py", line 778, in install
    requirement.uninstall(auto_confirm=True)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_install.py", line 754, in uninstall
    paths_to_remove.remove(auto_confirm)
  File "/usr/local/lib/python2.7/site-packages/pip/req/req_uninstall.py", line 115, in remove
    renames(path, new_path)
  File "/usr/local/lib/python2.7/site-packages/pip/utils/__init__.py", line 267, in renames
    shutil.move(old, new)
  File "/usr/local/Cellar/python@2/2.7.14_3/Frameworks/Python.framework/Versions/2.7/lib/python2.7/shutil.py", line 317, in move
    os.unlink(src)
OSError: [Errno 13] Permission denied: '/usr/local/lib/python2.7/site-packages/Selenium2Library/__init__.py'

**Comment by bartkl** [comment]
@mithunsureshqa You seem to require super user permissions since you have installed globally. Prefix your call to *pip* with ``sudo``, so that it will be run as super user. That should make things work.

**Comment by mithunsureshqa** [comment]
@bartkl thanks. somehow sudo also did not work. I tried to completely uninstall robotframework and reinstall. worked fine.

**Comment by lkrazy** [comment]
@outcatcher 
Thanks for your sharing :)

Can you share the guide line to generate static SeleniumLibrary 3.0 library?

**Comment by outcatcher** [comment]
@lkrazy 
I would suggest you to use fork by @youwi mentioned in https://github.com/millennialmedia/intellibot/issues/199. It's still workaround, but times better than mine :slightly_smiling_face: 

You can download `intellibot.jar` file from his repository and add it to Pycharm using `Install plugin from disk...` functionality on Plugins page in Pycharm settings

**Comment by lkrazy** [comment]
@outcatcher 
thanks for your suggestion :+1:

**Comment by Amy-Azazel** [comment]
I am facing the same issue with python 3.6.5 as interpreter, robot framework 3.0.3, seleniumlibrary 3.1.1 and Pycharm v2018.1.2. The workaround by using Selenium2Library with Python v2.7 does work but after each test-case execution, the IDE needs to be restarted as CTRL + CLICK doesn't work.
Request you to fix SeleniumLibrary as I have already made my whole project using this.

**Comment by outcatcher** [comment]
@Developer-Rathod  @Amy-Azazel Have you tried solution from #199 (using https://github.com/youwi/intellibot fork)?

**Comment by Amy-Azazel** [comment]
@outcatcher I did try this one, however some keywords still do not work like, click link, maximize browser window, etc

**Comment by outcatcher** [comment]
@Amy-Azazel 
I had same problem first, but Pycharm restart fixed this in my case 

If it still doesn't work — maybe "generating static library" solution mentioned in https://github.com/millennialmedia/intellibot/issues/191#issuecomment-381640140 can be useful to you (if you can tolerate such workaround 🙂 )

**Comment by outcatcher** [comment]
@Amy-Azazel Maybe @youwi can help you with problem with missing keywords with his fork?

**Comment by frankvanderkuur** [comment]
For all of you who have this problem, @youwi fixed this in his fork. [https://github.com/millennialmedia/intellibot/issues/199](url)

**Comment by bartkl** [comment]
@frankvanderkuur Don't you mean it works like a Pycharm? Oh man, that's really bad. And in public too. Anyways, that's some great news, thanks for sharing, and impressive work @youwi, thank you!

**Comment by nithinvargheese** [comment]
Hello... I still have issues in getting this correctly. I have installed the new Intellibot plugin. But still 'open browser' command shows 'keyword definition not found'.

PyCharm version : 2018.1.4 (Community Edition)
Windows 10
![screenshot_1](https://user-images.githubusercontent.com/32860685/41583017-dca21322-73c0-11e8-88fe-7ed2e6192a73.png)

Can somebody help?

**Comment by frankvanderkuur** [comment]
Hi Nithinvargheese, try installing en using de SeleniumLibrary instead of the Selenium2Library. I'll think that does the trick.

**Comment by nithinvargheese** [comment]
How can I get that happen?

pip install robotframework-selenium2library==1.8.0   --> is the command?

**Comment by frankvanderkuur** [comment]
pip install robotframework-seleniumlibrary should do the trick.

**Comment by nithinvargheese** [comment]
Tried. But same result. The issue exists

![image](https://user-images.githubusercontent.com/32860685/41636961-fc94a7cc-746e-11e8-95ac-8976425419e4.png)

**Comment by nithinvargheese** [comment]
@bartkl 
Thanks for the tips.

Same results again. Tried a new project too. But it does not seem to be working. Adding some screenshots for reference.
![secondproject](https://user-images.githubusercontent.com/32860685/41642645-911c17a6-7486-11e8-8142-8a7f93a72ba5.png)
![image](https://user-images.githubusercontent.com/32860685/41642666-a18d7012-7486-11e8-8faf-880f62540a2e.png)

**Comment by frankvanderkuur** [comment]
Hey @nithinvargheese 

You need to select the Existing Interpreter option and than the correct Python version where you installed the libraries in. If you only have 3.6 that's the correct one, but it could be you need to select 2.7.

**Comment by nithinvargheese** [comment]
Do you mean I need to install Python 2.7 version?

**Comment by frankvanderkuur** [comment]
That depends a bit on the robot libraries you want to use, but in most cases you will be able to use Python 3.x. What I mean is that if you have both 3.6 and 2.7 installed, the libraries could be installed in either of them when you are using PIP. If you have only one version of Python installed, just be sure you select the existing interpreter option instead of the new environment option.

**Comment by nithinvargheese** [comment]
I have deleted all the previous instances of Python from my PC and started from first. Same results.

**Comment by joe-riley** [comment]
This isn't working for me either using PyCharm Professional 181.5087 and with the following libs:
![image](https://user-images.githubusercontent.com/20083653/41944400-7c0d8ce8-795c-11e8-8296-5cf8044275ec.png)

I am not using a virtualenv (I would prefer to but the boss man sees no point) and this *shouldn't*(?) affect this.

**Comment by BShivShankar** [comment]
I had a solution about this

Click on Preferences -> Plugins
In search type 
> IntelliBot@SeleniumLibrary Patched'
Then Install it and restart it 
Now keyword errors disappeared

**Comment by joaonc** [comment]
Not sure if this has been brought up before, but there's a version of the plugin that contains the fix for this:  Search for **IntelliBot @SeleniumLibrary Patched** in the plugins repository.

https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched

I recall seeing the GitHub fork with this fix, but now I can't seem to find it.  I hope the author of this fix (Yu Cheng) didn't take it down as this plugin seems to have been abandoned but it's still the best Robot Framework plugin out there (tried a few).

Using PyCharm 2018.2 on Mac.

**Comment by abhishekatgit** [comment]
> Not sure if this has been brought up before, but there's a version of the plugin that contains the fix for this: Search for **IntelliBot @SeleniumLibrary Patched** in the plugins repository.
> 
> https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched
> 
> I recall seeing the GitHub fork with this fix, but now I can't seem to find it. I hope the author of this fix (Yu Cheng) didn't take it down as this plugin seems to have been abandoned but it's still the best Robot Framework plugin out there (tried a few).
> 
> Using PyCharm 2018.2 on Mac.

It worked for me thanks

**Comment by kostiantynvoiku** [comment]
> > Not sure if this has been brought up before, but there's a version of the plugin that contains the fix for this: Search for **IntelliBot @SeleniumLibrary Patched** in the plugins repository.
> > https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched
> > I recall seeing the GitHub fork with this fix, but now I can't seem to find it. I hope the author of this fix (Yu Cheng) didn't take it down as this plugin seems to have been abandoned but it's still the best Robot Framework plugin out there (tried a few).
> > Using PyCharm 2018.2 on Mac.
> 
> It worked for me thanks

@abhishekatgit @joaonc do you guys mean that you just installed `intellibot-seleniumlibrary-patched` and the problem with keyword definition is being fixed for you? 
It doesn't work for me.

**Comment by joaonc** [comment]
Are you using selenium 3 and PyCharm 2018?  I'm also using Python 3.6.  Not sure if that matters, especially if you have Python 2.7.

**Comment by kostiantynvoiku** [comment]
@joaonc yes:
```
PyCharm 2018.1.5 CE on MacOS 10.14
python 3.6.5
selenium 3.14.1  
robotframework 3.0.4
robotframework-seleniumlibrary 3.0.2 
```

I also tried `python2` and older `selenium` versions with `selenium2library`: got the same result "Keyword definition not found".

**Comment by max-silent** [comment]
@KonstantinxVx , this solution didn't work for me as well, until I tried following (maybe some steps are extra, but it's exactly what I did, before this problem disappeared):
1. Uninstall patched version of IntelliBot plugin.
2. Restart PyCharm.
3. Close PyCharm.
4. Install latest version of PyCharm (2018.2.4) on top of previous one (it was 2017.2.4 at my system) with agreeing  to import all settings/configuration from already installed version. 
5. Start PyCharm and install patched version of IntelliBot plugin, mentioned by @joaonc 
6. Restart PyCharm.
7. Open Project, which use "SeleniumLibrary" (exactly "SeleniumLibrary" (Selenium3), but not "Selenium2Library" (Selenium2), since this patched plugin does not resolve this issue for Selenium2).
8. Wait until indexing is complete (progress is displayed in status bar at the bottom of PyCharm window).

After all this steps - highlighting/links and auto-completion works fine for me and does not become broken after tests execution and PyCharm restarting.

Please, share if these steps resolved this issue for you. Have no another ideas, but just interested. ))

**_P.S.:_**
My current (successful :) ) configuration:
OS:                                                   Windows 7 Ultimate (x64)
PyCharm:                                          2018.2.4
IntelliBot @SeleniumLibrary Patched  0.10.143.381
Python:                                             3.6.3
robotframework                                3.0.4
robotframework-seleniumlibrary        3.1.1
selenium                                            3.12.0

**Comment by kostiantynvoiku** [comment]
@max-silent, thanks :) 

I re-installed all components from scratch few days ago and now it seems to be working (upgrading didn't help, only *re-installing* helped!).

My current configs:
Python 3.7.0
PyCharm 2018.2.4 CE
robotframework 3.0.4
robotframework-seleniumlibrary 3.2.0
selenium 3.14.1

**Comment by shress10** [comment]
> Not sure if this has been brought up before, but there's a version of the plugin that contains the fix for this: Search for **IntelliBot @SeleniumLibrary Patched** in the plugins repository.
> 
> https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched
> 
> I recall seeing the GitHub fork with this fix, but now I can't seem to find it. I hope the author of this fix (Yu Cheng) didn't take it down as this plugin seems to have been abandoned but it's still the best Robot Framework plugin out there (tried a few).
> 
> Using PyCharm 2018.2 on Mac.

This works!

**Comment by Nall11G** [comment]
Exactly, I also faced the same issue after upgrading the Robot framework, Python, and SeleniumLibrary. The workaround what I did, I have installed plugins in Pycharm editor (The Plugins is "IntelliBot @SeleniumLibrary Patched"). Now, all the selenium library keyword definitions are displaying.

**Installed version and details:**

Robot Framework 3.1.1 (Python 3.7.2 )
SeleniumLibrary3.3.1
Pycharm: pycharm-community-2018.3.5

Thanks,
Nallavan G

**Comment by amitsharmayogesh** [comment]
This configuration works for me  : 
 And I have disabled the Intellibot version.
![image](https://user-images.githubusercontent.com/14274384/56116757-7c8ecd80-5f1b-11e9-871b-a88fa0b6d0c5.png)

![image](https://user-images.githubusercontent.com/14274384/56116903-ce375800-5f1b-11e9-8de1-28591abafa13.png)

**Comment by chrisobrien1** [comment]
> This configuration works for me :
> And I have disabled the Intellibot version.
> ![image](https://user-images.githubusercontent.com/14274384/56116757-7c8ecd80-5f1b-11e9-871b-a88fa0b6d0c5.png)
> 
> ![image](https://user-images.githubusercontent.com/14274384/56116903-ce375800-5f1b-11e9-8de1-28591abafa13.png)

Worked a charm! Thank you!

**Comment by joshiShrikant** [comment]
> Hello... I still have issues in getting this correctly. I have installed the new Intellibot plugin. But still 'open browser' command shows 'keyword definition not found'.
> 
> PyCharm version : 2018.1.4 (Community Edition)
> Windows 10
> ![screenshot_1](https://user-images.githubusercontent.com/32860685/41583017-dca21322-73c0-11e8-88fe-7ed2e6192a73.png)
> 
> Can somebody help?

"o" should be capital

**Comment by ghost** [comment]
![image](https://user-images.githubusercontent.com/49985414/62424305-bb26de80-b6ea-11e9-8c36-0f8e5d69f28a.png)
![image](https://user-images.githubusercontent.com/49985414/62424312-dd206100-b6ea-11e9-8482-fca24f198d41.png)

getting keyword not found error with the above version .

Please help tried so many variant but still it is not working

**Comment by ctrongminh** [comment]
Hi All,

I use the Pycharm 2019.2 CE, and it also does not recognize the "Open browser" or "close browser".
I then install the Intellibot @SeleniumLibrary Patched plugins, and the problem is solved.

Python 2.7.13
robotframework==3.1.2
robotframework-seleniumlibrary==3.1.1
selenium==3.1.4

![image](https://user-images.githubusercontent.com/28387246/63318770-ce1fec80-c341-11e9-9999-fa8d038e71ab.png)

**Comment by mecanda12** [comment]
Python 3
robotframework==3.1.2
robotframework-seleniumlibrary==4
selenium==4

IntelliBot @SeleniumLibrary Patched is not working on above mention new version. Most of function work but CTRl + B does not work. 
Any another Plugin?

**Comment by JoelDelumen** [comment]
Works fine for me.

**Comment by mecanda12** [comment]
can you please explain the steps and add screen short of version, CTRL + B answer.

**Comment by mhofer117** [comment]
"IntelliBot @SeleniumLibrary Patched" is crashing for me with robotframework-seleniumlibrary==4 and message:
`com.intellij.psi.impl.file.PsiDirectoryImpl cannot be cast to com.jetbrains.python.psi.PyFile`

If I revert to robotframework-seleniumlibrary==3.3.1 and restart PyCharm it's working great.

**Comment by anushri** [comment]
Its crashing for me. any help ... if i can use any other plugin..

![image](https://user-images.githubusercontent.com/2067601/67177054-16c25780-f410-11e9-9f43-71b3c454b377.png)

![image](https://user-images.githubusercontent.com/2067601/67177064-25a90a00-f410-11e9-9542-692649e9d9e9.png)

**Comment by sakonachhoeurng** [comment]
Hello Anyone can help me, I also have problem on Mac OS that does not have auto-completed. I use
- Mac os 10.15
- Pycharm 2019.2
![Screen Shot 2019-10-25 at 9 42 12 AM](https://user-images.githubusercontent.com/12217854/67540852-3065e680-f711-11e9-981d-702fdb11db11.png)
Then my pycharm IDE get this error
![Screen Shot 2019-10-25 at 9 46 54 AM](https://user-images.githubusercontent.com/12217854/67540913-53909600-f711-11e9-89b8-343a515adec6.png)

**Comment by kostiantynvoiku** [comment]
@sakonachhoeurng it doesn't work properly with SeleniumLibrary ver. `> 4.0.0a2`.
Try release version `3.3.1` or alpha `4.0.0a2`.

**Comment by pkumar145678** [comment]
In Pycharm  Project Terminal install  seleniumlibrary -> pip install robotframework-seleniumlibrary    
and run  ->  robot <filename>.Robot

**Comment by parabaskar** [comment]
Ensure Project Interpreter is not empty.

**Comment by dubaksk** [comment]
We have the same issue for Selenium Library `> 4.0.0a2`: 
> Keyword definition not found

Robot itself is recognized and parsed properly.
Both plugins: [IntelliBot](https://plugins.jetbrains.com/plugin/7386-intellibot) and [IntelliBot @SeleniumLibrary Patched](https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched)  are not able to process Selenium.

System set up:

- pyCharm 2019.3
- Python 3.8
- robotframework==3.1.2
- robotframework-seleniumlibrary==4.1.0
- selenium==3

Are you still maintaining this plugin? Or it's time to find/move on different plugin?
Thanks for the info.

**Comment by JoelDelumen** [comment]
Same issue here with Ubuntu 18.

**Comment by neo502721** [comment]
> This configuration works for me :
> And I have disabled the Intellibot version.
> ![image](https://user-images.githubusercontent.com/14274384/56116757-7c8ecd80-5f1b-11e9-871b-a88fa0b6d0c5.png)
> 
> ![image](https://user-images.githubusercontent.com/14274384/56116903-ce375800-5f1b-11e9-8de1-28591abafa13.png)

Thanks!

**Comment by mikap72** [comment]
> > This configuration works for me :
> > And I have disabled the Intellibot version.
> > ![image](https://user-images.githubusercontent.com/14274384/56116757-7c8ecd80-5f1b-11e9-871b-a88fa0b6d0c5.png)
> > ![image](https://user-images.githubusercontent.com/14274384/56116903-ce375800-5f1b-11e9-8de1-28591abafa13.png)
> 
> Thanks!

This worked for me. Issues arose only after installing both SeleniumLibrary and RequestsLibrary to PyCharm. But as said, disabling IntelliBot Plugin reverted that.

THANK YOU!

**Comment by hardikgosai2310** [comment]
I am facing same issue but it got resolved by following steps.

Go to https://github.com/lte2000/intellibot/blob/develop/intellibot.jar

Download the jar file

Open PyCharm -> Settings -> Plugins -> Click on Setting Icon (Right side from the Installed tab) -> Select Install plugin from disk

Import the jar file in PyCharm editor

Click on Restart
