### ISSUE TITLE
Already disposed: Project (Disposed) error in Pycharm

### ISSUE THREAD

**Issue by neliCZka** [millennialmedia/intellibot#198]
Hi, I am using IntelliBot as a plugin to Pycharm and today resolving of usages stopped working and restart of Pycharm did not help.
This is in error log:

Already disposed: Project (Disposed) project_name
java.lang.AssertionError: Already disposed: Project (Disposed) project_name
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:164)
	at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:42)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.findSdkForNonModuleFile(PyBuiltinCache.java:112)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.findSdkForFile(PyBuiltinCache.java:103)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.getInstance(PyBuiltinCache.java:83)
	at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1281)
	at com.jetbrains.python.psi.impl.PyClassImpl.access$200(PyClassImpl.java:70)
	at com.jetbrains.python.psi.impl.PyClassImpl$NewStyleCachedValueProvider.compute(PyClassImpl.java:138)
	at com.jetbrains.python.psi.impl.PyClassImpl$NewStyleCachedValueProvider.compute(PyClassImpl.java:133)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.jetbrains.python.psi.impl.PyClassImpl.isNewStyleClass(PyClassImpl.java:1273)
	at com.jetbrains.python.psi.impl.PyClassImpl$CachedAncestorsProvider.fun(PyClassImpl.java:99)
	at com.jetbrains.python.psi.impl.PyClassImpl$CachedAncestorsProvider.fun(PyClassImpl.java:94)
	at com.jetbrains.python.psi.types.TypeEvalContextBasedCache.getValue(TypeEvalContextBasedCache.java:70)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorTypes(PyClassImpl.java:1504)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:320)
	at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1075)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:1066)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonWrapper.addDefinedKeywords(RobotPythonWrapper.java:70)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:37)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:39)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:389)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:366)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:236)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:208)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

java.lang.AssertionError: Already disposed: Project (Disposed) project_central_system_tests
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getComponent(ComponentManagerImpl.java:164)
	at com.intellij.openapi.roots.ProjectRootManager.getInstance(ProjectRootManager.java:42)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.findSdkForNonModuleFile(PyBuiltinCache.java:112)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.findSdkForFile(PyBuiltinCache.java:103)
	at com.jetbrains.python.psi.impl.PyBuiltinCache.getInstance(PyBuiltinCache.java:83)
	at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1281)
	at com.jetbrains.python.psi.impl.PyClassImpl.access$200(PyClassImpl.java:70)
	at com.jetbrains.python.psi.impl.PyClassImpl$NewStyleCachedValueProvider.compute(PyClassImpl.java:138)
	at com.jetbrains.python.psi.impl.PyClassImpl$NewStyleCachedValueProvider.compute(PyClassImpl.java:133)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.doCompute(PsiParameterizedCachedValue.java:45)
	at com.intellij.util.CachedValueBase.getValueWithLock(CachedValueBase.java:222)
	at com.intellij.psi.impl.PsiCachedValue.getValueWithLock(PsiCachedValue.java:60)
	at com.intellij.psi.impl.PsiParameterizedCachedValue.getValue(PsiParameterizedCachedValue.java:35)
	at com.jetbrains.python.psi.impl.PyClassImpl.isNewStyleClass(PyClassImpl.java:1273)
	at com.jetbrains.python.psi.impl.PyClassImpl$CachedAncestorsProvider.fun(PyClassImpl.java:99)
	at com.jetbrains.python.psi.impl.PyClassImpl$CachedAncestorsProvider.fun(PyClassImpl.java:94)
	at com.jetbrains.python.psi.types.TypeEvalContextBasedCache.getValue(TypeEvalContextBasedCache.java:70)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorTypes(PyClassImpl.java:1504)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:320)
	at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1075)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:1066)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonWrapper.addDefinedKeywords(RobotPythonWrapper.java:70)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:37)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:39)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:389)
	at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:366)
	at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:236)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:208)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:92)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:438)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1148)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:431)
	at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:548)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:493)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:430)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:406)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:142)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:237)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:404)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:165)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)

**Comment by darrylwhiting** [comment]
This issue also occurs in Windows 7 64 Bit with Intellibot Version - 0.10.143.381. Error is:

Already disposed: Project (Disposed) xxxxx_POC
java.lang.AssertionError: Already disposed: Project (Disposed) xxxxx_POC
	at com.intellij.openapi.components.impl.ComponentManagerImpl.lambda$getPicoContainer$2(ComponentManagerImpl.java:261)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:37)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:259)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:57)
	at com.intellij.openapi.components.ServiceManager.doGetService(ServiceManager.java:48)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:43)
	at com.jetbrains.python.psi.types.TypeEvalContext.getContextFromCache(TypeEvalContext.java:150)
	at com.jetbrains.python.psi.types.TypeEvalContext.codeInsightFallback(TypeEvalContext.java:126)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:249)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:1021)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:1012)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonWrapper.addDefinedKeywords(RobotPythonWrapper.java:70)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:37)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:39)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.walkKeyword(ResolverUtils.java:150)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.walkKeyword(ResolverUtils.java:157)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveVariableFromStatement(ResolverUtils.java:112)
	at com.millennialmedia.intellibot.psi.ref.RobotVariableReference.resolve(RobotVariableReference.java:25)
	at com.millennialmedia.intellibot.ide.inspections.compilation.RobotVariableNotFound.skip(RobotVariableNotFound.java:33)
	at com.millennialmedia.intellibot.ide.inspections.SimpleInspectionVisitor.visitElement(SimpleInspectionVisitor.java:23)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:82)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:70)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:286)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$3(LocalInspectionsPass.java:254)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1127)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:543)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:488)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:94)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:229)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:731)
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289)
	at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056)
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692)
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157)
