### ISSUE TITLE
intellibot breaks some PyCharm functions such as 'Find in Path'

### ISSUE THREAD

**Issue by DirkRichter** [millennialmedia/intellibot#203]
According to PyCharm logs, the robot-plugin 0.16.4 breaks some functionality such as Find in Path:
2018-06-06 10:02:16,110 [2143848] ERROR - aemon.impl.PassExecutorService - Element: class com.jetbrains.python.psi.impl.PyFileImpl because: different providers: SingleRootFileViewProvider{myVirtualFile=file://C:/Program Files (x86)/Python36-32/Lib/site-packages/robot/libraries/BuiltIn.py, content=VirtualFileContent{size=158119}}(b7eaffa); SingleRootFileViewProvider{myVirtualFile=file://C:/Program Files (x86)/Python36-32/Lib/site-packages/robot/libraries/BuiltIn.py, content=VirtualFileContent{size=158119}}(52fdf820) invalidated at: see attachment com.intellij.psi.PsiInvalidElementAccessException: Element: class com.jetbrains.python.psi.impl.PyFileImpl because: different providers: SingleRootFileViewProvider{myVirtualFile=file://C:/Program Files (x86)/Python36-32/Lib/site-packages/robot/libraries/BuiltIn.py, content=VirtualFileContent{size=158119}}(b7eaffa); SingleRootFileViewProvider{myVirtualFile=file://C:/Program Files (x86)/Python36-32/Lib/site-packages/robot/libraries/BuiltIn.py, content=VirtualFileContent{size=158119}}(52fdf820) invalidated at: see attachment at com.intellij.extapi.psi.StubBasedPsiElementBase.getNode(StubBasedPsiElementBase.java:135) at com.intellij.psi.PsiInvalidElementAccessException.getPsiInvalidationTrace(PsiInvalidElementAccessException.java:115) at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:77) at com.intellij.psi.PsiInvalidElementAccessException.<init>(PsiInvalidElementAccessException.java:49) at com.intellij.psi.util.PsiUtilCore.ensureValid(PsiUtilCore.java:485) at com.jetbrains.python.psi.impl.PyPsiUtils.assertValid(PyPsiUtils.java:570) at com.jetbrains.python.psi.impl.PyClassImpl.d(PyClassImpl.java:1673) at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1449) at com.jetbrains.python.psi.PyUtil.getNullableParameterizedCachedValue(PyUtil.java:819) at com.jetbrains.python.psi.PyUtil.getParameterizedCachedValue(PyUtil.java:797) at com.jetbrains.python.psi.impl.PyClassImpl.e(PyClassImpl.java:1445) at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorTypes(PyClassImpl.java:1440) at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:235) at com.jetbrains.python.psi.impl.PyClassImpl.a(PyClassImpl.java:1003) at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:994) at com.millennialmedia.intellibot.psi.ref.RobotPythonWrapper.addDefinedKeywords(RobotPythonWrapper.java:70) at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:37) at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:39) at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28) at com.intellij.codeInsight.TargetElementUtil.b(TargetElementUtil.java:378) at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:355) at com.intellij.codeInsight.TargetElementUtil.a(TargetElementUtil.java:227) at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:199) at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:94) at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:70) at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.c(PassExecutorService.java:437) at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1134) at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.b(PassExecutorService.java:430) at com.intellij.openapi.progress.impl.CoreProgressManager.a(CoreProgressManager.java:580) at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:525) at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:85) at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.a(PassExecutorService.java:429) at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.d(PassExecutorService.java:405) at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:143) at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:218) at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:403) at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:170) at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:289) at java.util.concurrent.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:1056) at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1692) at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:157) 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - PyCharm 2018.1.4 Build #PY-181.5087.37 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - JDK: 1.8.0_152-release 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - VM: OpenJDK 64-Bit Server VM 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - Vendor: JetBrains s.r.o 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - OS: Windows 10 2018-06-06 10:02:16,111 [2143849] ERROR - aemon.impl.PassExecutorService - Last Action: FindInPath

Here is my system spec:

PY-181.5087.37, JRE 1.8.0_152-release-1136-b39x64 JetBrains s.r.o, OS Windows 10(amd64) v10.0 , screens 1920x1080, 1920x1200, 1920x1200

**Comment by schnaser** [comment]
I am also affected by this. I'm on a Mac, using IntelliJ Ultimate. For me, the File menu doesn't work at all.

**Comment by stdedos** [comment]
Duplicate of #205 
(a solution is proposed)
