### ISSUE TITLE
Exceptionin plugin IntelliBot@SeleniumLibrary 0.10.142.381

### ISSUE THREAD

**Issue by marklane2001** [millennialmedia/intellibot#222]
Hi, I keep getting the below error in Pycharm when using the PlugIn. I have uninstalled and reinstalled but still occurring :

java.lang.ClassCastException: class com.intellij.psi.impl.file.PsiDirectoryImpl cannot be cast to class com.jetbrains.python.psi.PyFile (com.intellij.psi.impl.file.PsiDirectoryImpl and com.jetbrains.python.psi.PyFile are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @4b952a2d)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.findChildrenClass(HeadingImpl.java:441)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.collectImportFiles(HeadingImpl.java:386)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.getImportedFiles(HeadingImpl.java:349)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.getImportedFiles(RobotFileImpl.java:84)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:38)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:385)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:363)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:235)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:207)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)

**Comment by lucielavickova** [comment]
same happening for me. 
Using PyCharm 2019.2.1 (Community Edition)
Build #PC-192.6262.63, built on August 22, 2019
Runtime version: 11.0.3+12-b304.39 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0
GC: ParNew, ConcurrentMarkSweep
Memory: 1963M
Cores: 8
Registry: 
Non-Bundled Plugins: amailp.intellij.robot, com.andrey4623.rainbowcsv, com.millennialmedia.intellibot@SeleniumLibrary Patched, com.ppolivka.plugin.gitcleaner, net.seesharpsoft.intellij.plugins.csv, com.vladsch.idea.multimarkdown

**Comment by MartinBruska** [comment]
same issue for me

**Comment by lucielavickova** [comment]
hey guys, I finally resolved the issue by updating my JDK (JRE should be enough) - before, I was using Java 8 and it was failing, but once I updated to Java 13, I have no issues anymore! 
PyCharm is written in Java, so there might be some backward compatibility issue with older versions of Java.

**Comment by zastress** [comment]
If you are using seleniumlibrary 4.0.0 or higher, you can fix this by downgrading it.
`pip uninstall robotframework-seleniumlibrary
pip install robotframework-seleniumlibrary==3.3.1`

**Comment by lte2000** [comment]
Maybe you can try https://github.com/lte2000/intellibot
I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.

**Comment by lucielavickova** [comment]
> If you are using seleniumlibrary 4.0.0 or higher, you can fix this by downgrading it.
> `pip uninstall robotframework-seleniumlibrary pip install robotframework-seleniumlibrary==3.3.1`

thanks for the idea, however we got used to the new keywords and enhancements of selenium library 4 and we like it so much that downgrading it would cause more harm than good

**Comment by lucielavickova** [comment]
> Maybe you can try https://github.com/lte2000/intellibot
> I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.

hey, looks good... how can I start using it? Probably not directly from the PyCharm plugin marketplace, right...

**Comment by lte2000** [comment]
> 
> 
> > Maybe you can try https://github.com/lte2000/intellibot
> > I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.
> 
> hey, looks good... how can I start using it? Probably not directly from the PyCharm plugin marketplace, right...

It is not in the marketplace.
You can install the plugin manually. To do so you can either download and compile the project yourself. Or download the intellibot.jar file in the project (https://github.com/lte2000/intellibot/blob/develop/intellibot.jar). You can then install that plugin to your PyCharm by using the 'Install plugin from disk...' option.

**Comment by VinayKatamoni** [comment]
Its

> Maybe you can try https://github.com/lte2000/intellibot
> I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.

Tys Very Much...Its Workingg....

**Comment by jagdishprabhu75** [comment]
Plugin got installed but when IDE restarts it throws error
 
![image](https://user-images.githubusercontent.com/36630257/135808039-8ea949d8-b514-443e-bcb0-5c0cd4ba2a13.png)

**Comment by nanduIyer** [comment]
it is not working for me. It keeps coming. I did all the above said. 
Here is my version. 

PyCharm 2021.3.1 (Community Edition)
Build #PC-213.6461.77, built on December 28, 2021
Runtime version: 11.0.13+7-b1751.21 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 2048M
Cores: 12
Non-Bundled Plugins:
    String Manipulation (8.24.203.5981.1)
    izhangzhihao.rainbow.brackets (6.21)
    com.millennialmedia.intellibot@SeleniumLibrary Patched (0.10.143.381)

Here is the error I am getting

com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot@SeleniumLibrary Patched]
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.findTargetAdapter(ConstructorParameterResolver.kt:101)
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.access$findTargetAdapter(ConstructorParameterResolver.kt:1)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:49)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:876)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:401)
	at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:180)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:179)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:342)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:58)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:125)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:58)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:244)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:188)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$12(CoreProgressManager.java:624)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:698)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:646)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:623)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:175)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:244)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by nanduIyer** [comment]
![image](https://user-images.githubusercontent.com/95294558/148331861-2cb0d5b5-676c-4f2c-b09b-eb7c6eadebe1.png)

**Comment by Anujpalu24** [comment]
@nanduIyer : I am also facing the same issue you are facing, so if you got any solution please help : 

com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot@SeleniumLibrary Patched]
at com.intellij.serviceContainer.ConstructorParameterResolverKt.findTargetAdapter(ConstructorParameterResolver.kt:101)
at com.intellij.serviceContainer.ConstructorParameterResolverKt.access$findTargetAdapter(ConstructorParameterResolver.kt:1)

**Comment by nitleshcoer14** [comment]
Hi, I am getting the below error in Pycharm when using the PlugIn. I have uninstalled and reinstalled but still occurring :
**Exception in PluginIntelliBot #patched(0.16.191.8026)**

![-IDE Internal Errors](https://github.com/mtrubs/intellibot/assets/71215075/3d7af33b-d88f-4ce6-89b3-9199c02d156e)

java.lang.Throwable: Cannot distinguish StubFileElementTypes. This might worsen the performance. Providing unique externalId or adding a distinctive debugName when instantiating StubFileElementTypes can help. Version: psi.file:0:FILE -> [com.intellij.psi.tree.IStubFileElementType{psi.file;FILE;Language: Robot}, com.intellij.psi.tree.IStubFileElementType{psi.file;FILE;Language: ANY}]
	at com.intellij.openapi.diagnostic.Logger.error(Logger.java:202)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$determinePreviousFileElementType$8(PerFileElementTypeStubModificationTracker.java:203)
	at java.base/java.util.concurrent.ConcurrentHashMap.compute(ConcurrentHashMap.java:1916)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.determinePreviousFileElementType(PerFileElementTypeStubModificationTracker.java:199)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.fastCheck(PerFileElementTypeStubModificationTracker.java:101)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.lambda$endUpdatesBatch$2(PerFileElementTypeStubModificationTracker.java:76)
	at com.intellij.openapi.application.ReadAction.lambda$run$1(ReadAction.java:60)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:889)
	at com.intellij.openapi.application.ReadAction.compute(ReadAction.java:69)
	at com.intellij.openapi.application.ReadAction.run(ReadAction.java:59)
	at com.intellij.psi.stubs.PerFileElementTypeStubModificationTracker.endUpdatesBatch(PerFileElementTypeStubModificationTracker.java:75)
	at com.intellij.util.indexing.events.ChangedFilesCollector$4.endBatch(ChangedFilesCollector.java:246)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.lambda$endBatch$2(ChangedFilesCollector.java:283)
	at com.intellij.util.ConcurrencyUtil.withLock(ConcurrencyUtil.java:258)
	at com.intellij.util.indexing.events.ChangedFilesCollector$5.endBatch(ChangedFilesCollector.java:282)
	at com.intellij.util.indexing.events.VfsEventsMerger.processChanges(VfsEventsMerger.java:109)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesInReadAction(ChangedFilesCollector.java:265)
	at com.intellij.util.indexing.events.ChangedFilesCollector.processFilesToUpdateInReadAction(ChangedFilesCollector.java:224)
	at com.intellij.util.indexing.events.ChangedFilesCollector.ensureUpToDate(ChangedFilesCollector.java:190)
	at com.intellij.util.indexing.FileBasedIndexImpl.ensureUpToDate(FileBasedIndexImpl.java:836)
	at com.intellij.psi.stubs.StubIndexEx.getContainingIds(StubIndexEx.java:365)
	at com.intellij.psi.stubs.StubIndexEx.processElements(StubIndexEx.java:166)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:102)
	at com.intellij.psi.stubs.StubIndex.getElements(StubIndex.java:90)
	at com.jetbrains.python.psi.stubs.PyClassNameIndex.find(PyClassNameIndex.java:28)
	at com.jetbrains.python.psi.stubs.PyClassNameIndex.find(PyClassNameIndex.java:35)
	at com.millennialmedia.intellibot.psi.ref.PythonResolver.safeFindClass(PythonResolver.java:189)
	at com.millennialmedia.intellibot.psi.ref.PythonResolver.findClass(PythonResolver.java:89)
	at com.millennialmedia.intellibot.psi.ref.PythonResolver.findClass(PythonResolver.java:79)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.addBuiltInImports(RobotFileImpl.java:283)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.getImportedFiles(RobotFileImpl.java:138)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:55)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:31)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:176)
	at com.intellij.codeInsight.TargetElementUtilBase.doGetReferenceOrReferencedElement(TargetElementUtilBase.java:164)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferenceOrReferencedElement(TargetElementUtilBase.java:209)
	at com.intellij.codeInsight.TargetElementUtilBase.getReferencedElement(TargetElementUtilBase.java:253)
	at com.intellij.codeInsight.TargetElementUtilBase.doFindTargetElement(TargetElementUtilBase.java:232)
	at com.intellij.codeInsight.TargetElementUtilBase.findTargetElement(TargetElementUtilBase.java:297)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:147)
	at com.intellij.model.psi.impl.TargetsKt.fromTargetEvaluator(targets.kt:175)
	at com.intellij.model.psi.impl.TargetsKt.declarationsOrReferences(targets.kt:136)
	at com.intellij.model.psi.impl.TargetsKt.declaredReferencedData(targets.kt:42)
	at com.intellij.model.psi.impl.TargetsKt.targetSymbols(targets.kt:24)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.getTargetSymbols(IdentifierHighlighterPass.java:202)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.highlightReferencesAndDeclarations(IdentifierHighlighterPass.java:194)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:91)
	at com.intellij.codeInsight.highlighting.BackgroundHighlighter.lambda$submitIdentifierHighlighterPass$5(BackgroundHighlighter.java:203)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor.callWrapped(NonBlockingReadActionImpl.java:746)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$OTelMonitor$MonitoredComputation.call(NonBlockingReadActionImpl.java:778)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.insideReadAction(NonBlockingReadActionImpl.java:573)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$attemptComputation$3(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1100)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runInReadActionWithWriteActionPriority$0(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtilService.runActionAndCancelBeforeWrite(ProgressIndicatorUtilService.java:63)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runActionAndCancelBeforeWrite(ProgressIndicatorUtils.java:129)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.lambda$runWithWriteActionPriority$1(ProgressIndicatorUtils.java:110)
	at com.intellij.openapi.progress.ProgressManager.lambda$runProcess$1(ProgressManager.java:70)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:186)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$executeProcessUnderProgress$13(CoreProgressManager.java:604)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:679)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computeUnderProgress(CoreProgressManager.java:635)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:603)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:60)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:173)
	at com.intellij.openapi.progress.ProgressManager.runProcess(ProgressManager.java:70)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runWithWriteActionPriority(ProgressIndicatorUtils.java:107)
	at com.intellij.openapi.progress.util.ProgressIndicatorUtils.runInReadActionWithWriteActionPriority(ProgressIndicatorUtils.java:72)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.attemptComputation(NonBlockingReadActionImpl.java:537)
	at com.intellij.openapi.application.impl.NonBlockingReadActionImpl$Submission.lambda$transferToBgThread$1(NonBlockingReadActionImpl.java:444)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1136)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:635)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:702)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:699)
	at java.base/java.security.AccessController.doPrivileged(AccessController.java:399)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:699)
	at java.base/java.lang.Thread.run(Thread.java:833)

**Comment by khushbu07** [comment]
Facing same issue

**Comment by Nitumoon** [comment]
I am also facing same issue

![Image](https://github.com/user-attachments/assets/f9cbda6a-f06d-44ef-966a-640c9cd3512f)
