### ISSUE TITLE
Latest version is not compatible with SeleniumLibrary 4.0.0 or higher

### ISSUE THREAD

**Issue by zastress** [millennialmedia/intellibot#223]
Intellibot@SeleniumLibrayPached is no longer compatible with latest SeleniumLibrary (above 4.0.0).
Plugin crashes at Pycharm startup

**Comment by zastress** [comment]
Closed by mistake

**Comment by ghost** [comment]
Here is the error log for the plugin when it crashes...

**`java.lang.ClassCastException: class com.intellij.psi.impl.file.PsiDirectoryImpl cannot be cast to class com.jetbrains.python.psi.PyFile (com.intellij.psi.impl.file.PsiDirectoryImpl and com.jetbrains.python.psi.PyFile are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @3159c4b8)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.findChildrenClass(HeadingImpl.java:441)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.collectImportFiles(HeadingImpl.java:386)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.getImportedFiles(HeadingImpl.java:349)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.getImportedFiles(RobotFileImpl.java:84)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:38)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.intellij.codeInsight.TargetElementUtil.doGetReferenceOrReferencedElement(TargetElementUtil.java:385)
	at com.intellij.codeInsight.TargetElementUtil.getReferenceOrReferencedElement(TargetElementUtil.java:363)
	at com.intellij.codeInsight.TargetElementUtil.doFindTargetElement(TargetElementUtil.java:235)
	at com.intellij.codeInsight.TargetElementUtil.findTargetElement(TargetElementUtil.java:207)
	at com.intellij.codeInsight.daemon.impl.IdentifierHighlighterPass.doCollectInformation(IdentifierHighlighterPass.java:82)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)`**

**Comment by lte2000** [comment]
Maybe you can try https://github.com/lte2000/intellibot
I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.
C:\Python36\Scripts>pip show robotframework-seleniumlibrary
Name: robotframework-seleniumlibrary
Version: 4.1.0
Summary: Web testing library for Robot Framework
Home-page: https://github.com/robotframework/SeleniumLibrary
Author: Tatu Aalto
Author-email: aalto.tatu@gmail.com
License: Apache License 2.0
Location: c:\python36\lib\site-packages
Requires: robotframework, selenium
Required-by:

**Comment by zastress** [comment]
Ok, thanks. I will give it a try

**Comment by zastress** [comment]
@lte2000 I installed it on Pycharm 2019.2.3 and there is no more crash, indeed.
The problem is though that the commands from SeleniumLibrary 4.1.0 are not recognized by the plugin (CTRL+click on acommand does not do enything and all SeleniumLibrary commands are underlined with red color).
![2019-11-11_1232](https://user-images.githubusercontent.com/37159441/68580572-4f89a580-047f-11ea-9a09-94bd1159ccdb.png)

**Comment by lte2000** [comment]
> 
> 
> @lte2000 I installed it on Pycharm 2019.2.3 and there is no more crash, indeed.
> The problem is though that the commands from SeleniumLibrary 4.1.0 are not recognized by the plugin (CTRL+click on acommand does not do enything and all SeleniumLibrary commands are underlined with red color).
> ![2019-11-11_1232](https://user-images.githubusercontent.com/37159441/68580572-4f89a580-047f-11ea-9a09-94bd1159ccdb.png)

@zastress 
Have you selected the option in: Settings -> Languages & Frameworks -> Robot Options -> "Search Keywords in Sub-packages (e.g. SeleniumLibrary)"? The default is off.
See my screenshot for the effect of CTRL+ 
<img width="491" alt="Annotation 2019-11-11 211141" src="https://user-images.githubusercontent.com/35422407/68590035-846e1a80-04c8-11ea-8b8c-6f9c5060b234.png">

**Comment by zastress** [comment]
@lte2000, that worked. Thanks for the precious info :)

**Comment by zastress** [comment]
@lte2000, can you enable the "Issues" section inside your project for intellibot? There are some regressions that were observed and other problems that might be easier to fix if declared. Thanks.

**Comment by lte2000** [comment]
> 
> 
> @lte2000, can you enable the "Issues" section inside your project for intellibot? There are some regressions that were observed and other problems that might be easier to fix if declared. Thanks.

@zastress 
Enabled.
The latest version is dev-0.10.143.384. Some features are enhanced, some bugs and exceptions are fixed.

**Comment by RomanTatar-solar** [comment]
Can you please fix the "IntelliBot @SeleniumLibrary Patched"?
- I have version 0.10.143.381(latest release) and it crashes very often.
`
java.lang.ClassCastException: class com.intellij.psi.impl.file.PsiDirectoryImpl cannot be cast to class com.jetbrains.python.psi.PyFile (com.intellij.psi.impl.file.PsiDirectoryImpl and com.jetbrains.python.psi.PyFile are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @4566e5bd)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.findChildrenClass(HeadingImpl.java:441)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.collectImportFiles(HeadingImpl.java:386)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.getImportedFiles(HeadingImpl.java:349)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.getImportedFiles(RobotFileImpl.java:84)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:38)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:28)
	at com.millennialmedia.intellibot.ide.inspections.compilation.RobotKeywordNotFound.skip(RobotKeywordNotFound.java:28)
	at com.millennialmedia.intellibot.ide.inspections.SimpleInspectionVisitor.visitElement(SimpleInspectionVisitor.java:23)
	at com.intellij.psi.impl.PsiElementBase.accept(PsiElementBase.java:274)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:75)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:63)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:297)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$5(LocalInspectionsPass.java:265)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:156)
	at com.intellij.util.AstLoadingFilter.forceAllowTreeLoading(AstLoadingFilter.java:148)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$null$6(LocalInspectionsPass.java:262)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:127)
	at com.intellij.util.AstLoadingFilter.disallowTreeLoading(AstLoadingFilter.java:116)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.lambda$visitPriorityElementsAndInit$7(LocalInspectionsPass.java:262)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:133)
	at com.intellij.concurrency.ApplierCompleter.tryToExecAllList(ApplierCompleter.java:231)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:159)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1101)
	at com.intellij.concurrency.ApplierCompleter.lambda$wrapInReadActionAndIndicator$1(ApplierCompleter.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:116)
	at com.intellij.concurrency.ApplierCompleter.lambda$compute$0(ApplierCompleter.java:96)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:96)
	at java.base/java.util.concurrent.CountedCompleter.exec(CountedCompleter.java:746)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.helpCC(ForkJoinPool.java:1115)
	at java.base/java.util.concurrent.ForkJoinPool.awaitJoin(ForkJoinPool.java:1687)
	at java.base/java.util.concurrent.ForkJoinTask.get(ForkJoinTask.java:1039)
	at com.intellij.concurrency.JobLauncherImpl.invokeConcurrentlyUnderProgress(JobLauncherImpl.java:58)
	at com.intellij.concurrency.JobLauncher.invokeConcurrentlyUnderProgress(JobLauncher.java:58)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.visitPriorityElementsAndInit(LocalInspectionsPass.java:268)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.inspect(LocalInspectionsPass.java:200)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:119)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:84)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:55)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$null$1(PassExecutorService.java:429)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$doRun$2(PassExecutorService.java:422)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:421)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.lambda$run$0(PassExecutorService.java:397)
	at com.intellij.openapi.application.impl.ReadMostlyRWLock.executeByImpatientReader(ReadMostlyRWLock.java:164)
	at com.intellij.openapi.application.impl.ApplicationImpl.executeByImpatientReader(ApplicationImpl.java:204)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:395)
	at com.intellij.concurrency.JobLauncherImpl$VoidForkJoinTask$1.exec(JobLauncherImpl.java:161)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
`

**Comment by sharikavishak** [comment]
> Maybe you can try https://github.com/lte2000/intellibot
> I use PyCharm 2019.1.3, and robotframework-seleniumlibrary 4.1.0, no exception on a basic test.
> C:\Python36\Scripts>pip show robotframework-seleniumlibrary
> Name: robotframework-seleniumlibrary
> Version: 4.1.0
> Summary: Web testing library for Robot Framework
> Home-page: https://github.com/robotframework/SeleniumLibrary
> Author: Tatu Aalto
> Author-email: [aalto.tatu@gmail.com](mailto:aalto.tatu@gmail.com)
> License: Apache License 2.0
> Location: c:\python36\lib\site-packages
> Requires: robotframework, selenium
> Required-by:



> > @lte2000 I installed it on Pycharm 2019.2.3 and there is no more crash, indeed.
> > The problem is though that the commands from SeleniumLibrary 4.1.0 are not recognized by the plugin (CTRL+click on acommand does not do enything and all SeleniumLibrary commands are underlined with red color).
> > ![2019-11-11_1232](https://user-images.githubusercontent.com/37159441/68580572-4f89a580-047f-11ea-9a09-94bd1159ccdb.png)
> 
> @zastress
> Have you selected the option in: Settings -> Languages & Frameworks -> Robot Options -> "Search Keywords in Sub-packages (e.g. SeleniumLibrary)"? The default is off.
> See my screenshot for the effect of CTRL+

I was facing the same issue and this worked for me too. Thanks a lot !!

**Comment by zastress** [comment]
Yep, got it working. Thanks,

**Comment by frankvanderkuur** [comment]
The lte2000 fork fixed the problem for me asvwell, thanks!

**Comment by RomanTatar-solar** [comment]
[lte2000 fork](https://github.com/lte2000/intellibot) works with PyCharm 2020.1.2 + Python 3.8 + robotframework-seleniumlibrary 4.4.0
