### ISSUE TITLE
Internal IDE Error(Class Cast Exception)

### ISSUE THREAD

**Issue by Abhi904485** [millennialmedia/intellibot#225]
Pycharm version: 2019.2.5 CE
OS: Mac 10

java.lang.ClassCastException: class com.intellij.psi.impl.file.PsiDirectoryImpl cannot be cast to class com.jetbrains.python.psi.PyFile (com.intellij.psi.impl.file.PsiDirectoryImpl and com.jetbrains.python.psi.PyFile are in unnamed module of loader com.intellij.util.lang.UrlClassLoader @29ca901e)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.findChildrenClass(HeadingImpl.java:441)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.collectImportFiles(HeadingImpl.java:386)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.getImportedFiles(HeadingImpl.java:349)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.collectVariables(HeadingImpl.java:133)
	at com.millennialmedia.intellibot.psi.element.HeadingImpl.getDefinedVariables(HeadingImpl.java:115)
	at com.millennialmedia.intellibot.psi.element.RobotFileImpl.getDefinedVariables(RobotFileImpl.java:48)
	at com.millennialmedia.intellibot.ide.RobotCompletionContributor.addRobotVariables(RobotCompletionContributor.java:197)
	at com.millennialmedia.intellibot.ide.RobotCompletionContributor.access$800(RobotCompletionContributor.java:30)
	at com.millennialmedia.intellibot.ide.RobotCompletionContributor$7.addCompletions(RobotCompletionContributor.java:135)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.millennialmedia.intellibot.ide.RobotCompletionContributor.fillCompletionVariants(RobotCompletionContributor.java:263)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:148)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:141)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$1.addCompletions(LiveTemplateCompletionContributor.java:77)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:40)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:150)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:63)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:119)
	at com.intellij.codeInsight.completion.impl.CompletionServiceImpl.performCompletion(CompletionServiceImpl.java:55)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:824)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.runContributors(CompletionProgressIndicator.java:809)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$null$5(CodeCompletionHandlerBase.java:325)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$tryReadOrCancel$5(CompletionThreading.java:172)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1106)
	at com.intellij.codeInsight.completion.AsyncCompletion.tryReadOrCancel(CompletionThreading.java:170)
	at com.intellij.codeInsight.completion.CodeCompletionHandlerBase.lambda$startContributorThread$6(CodeCompletionHandlerBase.java:317)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:95)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:169)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:591)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:537)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:156)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$1(CompletionThreading.java:91)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:294)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by lte2000** [comment]
@Abhi904485 Your issue seems same as #223 .
Please try the update in https://github.com/lte2000/intellibot/files/3858687/intellibot.zip

**Comment by Abhi904485** [comment]
hi i checked now issue is resolved

thanks

**Comment by Abhi904485** [comment]
hi Millennialmedia/Intellibot
Now Class cast exception is not comming but , In Robot file i imported some
Library now on using command + B it is showing file not found . but in
previous version it is happening and class cast Exception is coming . can
you please look into the issue.

**Comment by lte2000** [comment]
@Abhi904485 There is a new setting related to this. Please refer to https://github.com/lte2000/intellibot/issues/1

**Comment by Abhi904485** [comment]
i checked and put transitive import value to 99 , Library are resolving but
Resource and Variables are not resolving , if i am giving absolute path
then it resolved , in previous version Variables and Resource is also
resolving .
