### ISSUE TITLE
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl 

### ISSUE THREAD

**Issue by Abhi904485** [millennialmedia/intellibot#228]
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:59)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:45)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.instantiateClassWithConstructorInjection(PlatformComponentManagerImpl.kt:505)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:72)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:65)
	at com.intellij.serviceContainer.PlatformComponentManagerImpl.createComponents(PlatformComponentManagerImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:295)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:315)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.convertAndLoadProject(ProjectManagerImpl.java:624)
	at com.intellij.platform.PlatformProjectOpenProcessor.prepareProject(PlatformProjectOpenProcessor.java:315)
	at com.intellij.platform.PlatformProjectOpenProcessor.lambda$openExistingProject$0(PlatformProjectOpenProcessor.java:241)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$1.run(ProjectFrameAllocator.kt:77)
	at com.intellij.openapi.progress.impl.CoreProgressManager$2.run(CoreProgressManager.java:247)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:888)
	at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:441)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:163)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:585)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:531)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:59)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:150)
	at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$4(ApplicationImpl.java:441)
	at com.intellij.util.ConcurrencyUtil.runUnderThreadName(ConcurrencyUtil.java:221)
	at com.intellij.util.ConcurrencyUtil.lambda$underThreadNameRunnable$3(ConcurrencyUtil.java:209)
	at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:238)
	at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
	at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)

**Comment by Abhi904485** [comment]
pycharm version 2019.1.3 
python 2.7.15
intellibot version : 0.10.143.381

**Comment by Flukester69** [comment]
pycharm 2019.3.1
python 3.7.4
intellibot version 0.10.143.381

**Comment by TomskDiver** [comment]
Duplicate of #226

**Comment by lte2000** [comment]
Maybe same issue of [#6](https://github.com/lte2000/intellibot/issues/6)
Please try forked plugin https://github.com/lte2000/intellibot
Download the intellibot.jar file.
Then install the plugin to your IDE by using the 'Install plugin from disk...' option.

**Comment by bltzr75** [comment]
> Install plugin from disk

It worked for me! Ty

**Comment by thimira007** [comment]
> Maybe same issue of [#6](https://github.com/lte2000/intellibot/issues/6)
> Please try forked plugin https://github.com/lte2000/intellibot
> Download the intellibot.jar file.
> Then install the plugin to your IDE by using the 'Install plugin from disk...' option.

Worked for me.. Thanks

**Comment by Abhi904485** [comment]
After installing forked plugin it is breaking my existing things it is not recognising import which was recognised before for Example :

Library		api.JobSubmitter
Library  	        AuditCrateHelper
Library		policyevaluator.ConfigDataGenerator
Library		policyevaluator.AuditPolicyValidator  

In existing plugin it is giving exception getComponentAdapterOfType  but  when i click in cmd + click i am going to Appropriate file 

After updating plugin to forked one . i am not getting any exception but my navigation functionality is broken . And whole file is with errors because it is not able to check whether that function is in python file which is declared in Library.


And i give recursive things to 99 also that also not work .

**Comment by abduljaved2605** [comment]
Clear your cache, it worked for me

**Comment by Abhi904485** [comment]
[intellibot.jar.zip](https://github.com/mtrubs/intellibot/files/7100715/intellibot.jar.zip)

**Comment by Flukester69** [comment]
https://github.com/lte2000/intellibot, grab the jar there.

...is what I use and works as expected. Just wish it did a better job of looking up things.
