### ISSUE TITLE
Error when starting pycharm

### ISSUE THREAD

**Issue by petermant** [millennialmedia/intellibot#234]
When I start pycharm via the console, I get the following error:

2020-06-19 20:10:11,143 [   2475]   WARN - Container.ComponentManagerImpl - Do not use constructor injection (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager) 
2020-06-19 20:10:11,143 [   2475]  ERROR - Container.ComponentManagerImpl - getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot] 
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:59)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:61)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:660)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:115)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:69)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:62)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:261)
	at com.intellij.openapi.project.impl.ProjectImpl.init(ProjectImpl.java:269)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:321)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.convertAndLoadProject(PlatformProjectOpenProcessor.kt:404)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.prepareProject(PlatformProjectOpenProcessor.kt:299)
	at com.intellij.platform.PlatformProjectOpenProcessorKt.access$prepareProject(PlatformProjectOpenProcessor.kt:1)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:186)
	at com.intellij.platform.PlatformProjectOpenProcessor$Companion$openExistingProject$$inlined$runInAutoSaveDisabledMode$lambda$1.invoke(PlatformProjectOpenProcessor.kt:57)
	at com.intellij.platform.ProjectUiFrameAllocator$run$1$progressTask$1.run(ProjectFrameAllocator.kt:85)
	at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:932)
	at com.intellij.openapi.progress.impl.CoreProgressManager$4.run(CoreProgressManager.java:482)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$new$0(ProgressRunner.java:77)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$null$3(ProgressRunner.java:233)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:166)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:627)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:572)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:61)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:153)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:233)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.lang.Thread.run(Thread.java:834)
2020-06-19 20:10:11,145 [   2477]  ERROR - Container.ComponentManagerImpl - PyCharm 2020.1.2  Build #PC-201.7846.77 
2020-06-19 20:10:11,145 [   2477]  ERROR - Container.ComponentManagerImpl - JDK: 11.0.7; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o. 
2020-06-19 20:10:11,146 [   2478]  ERROR - Container.ComponentManagerImpl - OS: Linux 
2020-06-19 20:10:11,146 [   2478]  ERROR - Container.ComponentManagerImpl - Plugin to blame: IntelliBot version: 0.10.143.381

**Comment by Abhi904485** [comment]
https://github.com/mtrubs/intellibot/issues/228#issuecomment-911909183
