### ISSUE TITLE
issue with " IntelliBot @SeleniumLibrary Patched"

### ISSUE THREAD

**Issue by judahshaik** [millennialmedia/intellibot#241]
I am unable to use " IntelliBot @SeleniumLibrary Patched" plugin in PyCharm community edition 2021.1.1 and Python 3.9 Pycharm throwing an error like the below screenshot

![RobotPluginError1](https://user-images.githubusercontent.com/85666435/121636998-5be44300-caa6-11eb-9e53-6ca088c42b4a.JPG)

enter image description here 

It seems this plugin is not a production of JetBrains and referred me to report it, however i have downloaded from the official and install plugin through disk site( https://plugins.jetbrains.com/plugin/10700-intellibot-seleniumlibrary-patched )

It's the same issue if I download from Marketplace within PyCharm.

Also auto suggestions for .robot files are not showing and it's not working. please lookinto this I have already installed all required packages  as below:
Pycharm  IDE    2021.1.1
Python                      3.9
py                              1.10.0 
requests                        2.25.1 
robotframework                  4.0.3 
robotframework-jsonlibrary      0.3.1
robotframework-pythonlibcore    2.2.1
robotframework-requests         0.9.1 
robotframework-selenium2library 3.0.0 
robotframework-seleniumlibrary  3.3.1 
selenium                        3.141.0 
setuptools                      56.0.0

Thanks in advance.

**Comment by GPatrich** [comment]
I am experiencing same issue:
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot@SeleniumLibrary Patched]
	at com.intellij.serviceContainer.ConstructorParameterResolver.findTargetAdapter(ConstructorParameterResolver.kt:111)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:59)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:771)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:110)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:64)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:57)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:340)
	at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:177)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:175)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:263)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:55)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProjectAsync$1.invoke(ProjectManagerExImpl.kt:111)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$openProjectAsync$1.invoke(ProjectManagerExImpl.kt:55)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:93)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:70)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:228)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:178)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:688)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:634)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:64)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:165)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:228)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
	at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:668)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1$1.run(Executors.java:665)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.util.concurrent.Executors$PrivilegedThreadFactory$1.run(Executors.java:665)
	at java.base/java.lang.Thread.run(Thread.java:829)

PyCharm IDE 2021.1.2 (Community)

**Comment by pengtao-zheng** [comment]
I am experiencing same issue:
Cannot create configurable

com.intellij.diagnostic.PluginException: Cannot create class com.millennialmedia.intellibot.ide.config.RobotConfiguration (classloader=PluginClassLoader(plugin=PluginDescriptor(name=IntelliBot @SeleniumLibrary Patched, id=com.millennialmedia.intellibot@SeleniumLibrary Patched, descriptorPath=plugin.xml, path=~\AppData\Roaming\JetBrains\PyCharmCE2021.1\plugins\intellibot .jar, version=0.10.143.381, package=null), packagePrefix=null, instanceId=36, state=active))
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:763)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:781)
	at com.intellij.openapi.options.ConfigurableEP$ClassProducer.createElement(ConfigurableEP.java:440)
	at com.intellij.openapi.options.ConfigurableEP.createConfigurable(ConfigurableEP.java:346)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.createConfigurable(ConfigurableWrapper.java:42)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getConfigurable(ConfigurableWrapper.java:116)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.cast(ConfigurableWrapper.java:91)
	at com.intellij.openapi.options.ex.ConfigurableWrapper.getId(ConfigurableWrapper.java:211)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.groupConfigurables(ConfigurableExtensionPointUtil.java:264)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:126)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.lambda$getConfigurableGroup$1(ConfigurableExtensionPointUtil.java:116)
	at com.intellij.openapi.util.ClearableLazyValue$2.compute(ClearableLazyValue.java:26)
	at com.intellij.openapi.util.ClearableLazyValue.getValue(ClearableLazyValue.java:39)
	at com.intellij.openapi.util.AtomicClearableLazyValue.getValue(AtomicClearableLazyValue.java:9)
	at com.intellij.openapi.options.ex.EpBasedConfigurableGroup.<init>(EpBasedConfigurableGroup.kt:111)
	at com.intellij.openapi.options.ex.ConfigurableExtensionPointUtil.getConfigurableGroup(ConfigurableExtensionPointUtil.java:114)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.getConfigurableGroups(ShowSettingsUtilImpl.java:53)
	at com.intellij.ide.actions.ShowSettingsAction.perform(ShowSettingsAction.java:55)
	at com.intellij.ide.actions.ShowSettingsAction.actionPerformed(ShowSettingsAction.java:42)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.lambda$performActionDumbAware$5(ActionUtil.java:273)
	at com.intellij.util.SlowOperations.lambda$allowSlowOperations$0(SlowOperations.java:77)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:64)
	at com.intellij.util.SlowOperations.allowSlowOperations(SlowOperations.java:76)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:273)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.lambda$actionPerformed$0(ActionMenuItem.java:310)
	at com.intellij.openapi.wm.impl.FocusManagerImpl.runOnOwnContext(FocusManagerImpl.java:286)
	at com.intellij.openapi.wm.impl.IdeFocusManagerImpl.runOnOwnContext(IdeFocusManagerImpl.java:77)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem$ActionTransmitter.actionPerformed(ActionMenuItem.java:299)
	at java.desktop/javax.swing.AbstractButton.fireActionPerformed(AbstractButton.java:1967)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.lambda$fireActionPerformed$0(ActionMenuItem.java:110)
	at com.intellij.openapi.application.TransactionGuardImpl.performUserActivity(TransactionGuardImpl.java:95)
	at com.intellij.openapi.actionSystem.impl.ActionMenuItem.fireActionPerformed(ActionMenuItem.java:110)
	at com.intellij.ui.plaf.beg.BegMenuItemUI.doClick(BegMenuItemUI.java:515)
	at com.intellij.ui.plaf.beg.BegMenuItemUI$MyMouseInputHandler.mouseReleased(BegMenuItemUI.java:545)
	at java.desktop/java.awt.Component.processMouseEvent(Component.java:6652)
	at java.desktop/javax.swing.JComponent.processMouseEvent(JComponent.java:3345)
	at java.desktop/java.awt.Component.processEvent(Component.java:6417)
	at java.desktop/java.awt.Container.processEvent(Container.java:2263)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5027)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2321)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4918)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4547)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4488)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2307)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2784)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4859)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:778)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:727)
	at java.desktop/java.awt.EventQueue$4.run(EventQueue.java:721)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:95)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:751)
	at java.desktop/java.awt.EventQueue$5.run(EventQueue.java:749)
	at java.base/java.security.AccessController.doPrivileged(Native Method)
	at java.base/java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:85)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:748)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:969)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.java:906)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:836)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$8(IdeEventQueue.java:449)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:808)
	at com.intellij.ide.IdeEventQueue.lambda$dispatchEvent$9(IdeEventQueue.java:448)
	at com.intellij.openapi.application.impl.ApplicationImpl.runIntendedWriteActionOnCurrentThread(ApplicationImpl.java:781)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:502)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:203)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:124)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:109)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:90)
Caused by: java.lang.IllegalArgumentException: argument type mismatch
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance0(Native Method)
	at java.base/jdk.internal.reflect.NativeConstructorAccessorImpl.newInstance(NativeConstructorAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingConstructorAccessorImpl.newInstance(DelegatingConstructorAccessorImpl.java:45)
	at java.base/java.lang.reflect.Constructor.newInstance(Constructor.java:490)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClass(ComponentManagerImpl.kt:742)
	... 71 more

**Comment by loritempleton** [comment]
Is there any plans to fix this for Pycharms version 2021.2? 
I'm unable to utilize this plug in at all I've had to un-install the plug in or it freezes my IDE with the same error messages above, and I have to do a hard reboot and uninstall the plugin to be able to continue using pycharms.
Running PyCharms 2021.4746.96 on Mac.

**Comment by iamcarlp** [comment]
com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot@SeleniumLibrary Patched]
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.findTargetAdapter(ConstructorParameterResolver.kt:101)
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.access$findTargetAdapter(ConstructorParameterResolver.kt:1)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:49)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:877)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:35)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstanceUncached(BaseComponentAdapter.kt:113)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance(BaseComponentAdapter.kt:67)
	at com.intellij.serviceContainer.BaseComponentAdapter.getInstance$default(BaseComponentAdapter.kt:60)
	at com.intellij.serviceContainer.ComponentManagerImpl.createComponents(ComponentManagerImpl.kt:407)
	at com.intellij.openapi.project.impl.ProjectExImpl.init(ProjectExImpl.kt:183)
	at com.intellij.openapi.project.impl.ProjectManagerImpl.initProject(ProjectManagerImpl.java:178)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.prepareProject(ProjectManagerExImpl.kt:250)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl.access$prepareProject(ProjectManagerExImpl.kt:57)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:119)
	at com.intellij.openapi.project.impl.ProjectManagerExImpl$doOpenAsync$1.invoke(ProjectManagerExImpl.kt:57)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:94)
	at com.intellij.openapi.project.impl.ProjectUiFrameAllocator$run$progressRunner$1.apply(ProjectFrameAllocator.kt:71)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$3(ProgressRunner.java:243)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:183)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:705)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:647)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:63)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:170)
	at com.intellij.openapi.progress.impl.ProgressRunner.lambda$submit$4(ProgressRunner.java:243)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.run(CompletableFuture.java:1700)
	at java.base/java.util.concurrent.CompletableFuture$AsyncSupply.exec(CompletableFuture.java:1692)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1020)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1656)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1594)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:183)

**Comment by iamcarlp** [comment]
@judahshaik @GPatrich @loritempleton @pengtao-zheng

You can download the jar below then install from Disk
https://github.com/lte2000/intellibot/blob/master/intellibot.jar

**Comment by lte2000** [comment]
> 
> 
> @judahshaik @GPatrich @loritempleton @pengtao-zheng
> 
> You can download the jar below then install from Disk
> https://github.com/lte2000/intellibot/blob/master/intellibot.jar

This plugin has been published in Jetbrains Marketplace, https://plugins.jetbrains.com/plugin/17424-intellibot-patched
Just search **"IntelliBot #patched"**  and install it directly under Marketplace tab in the IDE plugin manager.

**Comment by Lamiamrad** [comment]
> > @judahshaik @GPatrich @loritempleton @pengtao-zheng
> > You can download the jar below then install from Disk
> > https://github.com/lte2000/intellibot/blob/master/intellibot.jar
> 
> This plugin has been published in Jetbrains Marketplace, https://plugins.jetbrains.com/plugin/17424-intellibot-patched Just search **"IntelliBot #patched"** and install it directly under Marketplace tab in the IDE plugin manager.

Hi @judahshaik,

Actually I have tried this solution but it seems that it's not working and I am getting this error.

<img width="1035" alt="Capture d’écran 2021-11-18 à 17 44 09" src="https://user-images.githubusercontent.com/12755142/142458920-abf33e8b-3b52-4e11-be70-3dedf6a2e462.png">

**Comment by nanduIyer** [comment]
I am facing the similar issue

Any comments

**Comment by AhmedGulfam** [comment]
Hi,
I am also getting the above-mentioned error but did not find any solution so far. 
Getting the below error - after installing the "IntelliBot #patched" from Marketplace.
The IDE failed to install or update some plugins.
Please try again, and if the problem persists, please report it
to https://jb.gg/ide/critical-startup-errors

The cause: java.nio.file.FileAlreadyExistsException: C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar

**Comment by lte2000** [comment]
> Hi, I am also getting the above-mentioned error but did not find any solution so far. Getting the below error - after installing the "IntelliBot #patched" from Marketplace. The IDE failed to install or update some plugins. Please try again, and if the problem persists, please report it to https://jb.gg/ide/critical-startup-errors
> 
> The cause: java.nio.file.FileAlreadyExistsException: C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar

Maybe you can try uninstall the plugin IntelliBot first. Or manually delete the file "C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar", and restart the pycharm.
Then "IntelliBot #patched" from Marketplace.

**Comment by AhmedGulfam** [comment]
Hi,
I did it as advised above but still facing the same issue

The IDE failed to install or update some plugins.
Please try again, and if the problem persists, please report it
to https://jb.gg/ide/critical-startup-errors

The cause: java.nio.file.FileAlreadyExistsException: C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar

Pycharm is not recognizing the keywords and is not displaying the intellisense methods.

any further updates

**Comment by lte2000** [comment]
Force delete the file C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar
Restart Pycharm.
Does the file C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar still exist?

**Comment by AhmedGulfam** [comment]
Now I don't see the intellijot.jar file in the location now

**Comment by lte2000** [comment]
> Now I don't see the intellijot.jar file in the location now

How about install "IntelliBot #patched" now?

**Comment by AhmedGulfam** [comment]
Hi,

I just finished the installation of "IntelliBot #patched" from the marketplace. The error IDE failed did not appear at this time. But .robot file are not getting recognized. I cannot create new robot files, no syntax highlighting.

**Comment by lte2000** [comment]
>But .robot file are not getting recognized. 

It is so odd. 
Can you check the file "C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\options\filetypes.xml", iIs "robot" in removed_mapping?

And check the setting in Pycharm: Editor -> File Types, in "Recognized File Types", find "Robot Framework Test Data", then in Registered Patterns, check whether "*.robot" is there. If not, add it.

**Comment by srisha95** [comment]
I was having same issue , but the issue resolved when I installed intellibot from disk, download the jar from this location:
https://github.com/lte2000/intellibot/blob/master/intellibot.jar

**Comment by islamyassien** [comment]
I faced the same issue and it resolved when I installed intellibot from disk but "Library  SeleniumLibrary" isn't recognized.

<img width="960" alt="pycharm issue" src="https://user-images.githubusercontent.com/85640948/169057323-58a8aef8-3781-4bde-a981-791b95e3c5dd.PNG">

**Comment by zilpilwarb** [comment]
@srisha95 Thank you for this solution it worked at first only, no struggle.
Thank you again!!!

**Comment by tamizhselvan25** [comment]
@srisha95 how to add this plugin https://github.com/lte2000/intellibot/blob/master/intellibot.jar in pycharm

**Comment by indraw705** [comment]
Same happening with me 

com.intellij.diagnostic.PluginException: getComponentAdapterOfType is used to get com.intellij.psi.impl.PsiManagerImpl (requestorClass=com.millennialmedia.intellibot.psi.RobotPsiManager, requestorConstructor=public com.millennialmedia.intellibot.psi.RobotPsiManager(com.intellij.psi.impl.PsiManagerImpl)).

Probably constructor should be marked as NonInjectable. [Plugin: com.millennialmedia.intellibot@SeleniumLibrary Patched]
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.findTargetAdapter(ConstructorParameterResolver.kt:101)
	at com.intellij.serviceContainer.ConstructorParameterResolverKt.access$findTargetAdapter(ConstructorParameterResolver.kt:1)
	at com.intellij.serviceContainer.ConstructorParameterResolver.resolveInstance(ConstructorParameterResolver.kt:49)
	at com.intellij.serviceContainer.ConstructorInjectionKt.instantiateUsingPicoContainer(constructorInjection.kt:81)
	at com.intellij.serviceContainer.ComponentManagerImpl.instantiateClassWithConstructorInjection(ComponentManagerImpl.kt:1041)
	at com.intellij.serviceContainer.MyComponentAdapter.doCreateInstance(MyComponentAdapter.kt:36)

**Comment by EsperasDonna** [comment]
As of today, yes, this is still occured.

**Comment by venu1394** [comment]
> > Hi, I am also getting the above-mentioned error but did not find any solution so far. Getting the below error - after installing the "IntelliBot #patched" from Marketplace. The IDE failed to install or update some plugins. Please try again, and if the problem persists, please report it to https://jb.gg/ide/critical-startup-errors
> > The cause: java.nio.file.FileAlreadyExistsException: C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar
> 
> **Maybe you can try uninstall the plugin IntelliBot first. Or manually delete the file "C:\Users\Gulfam\AppData\Roaming\JetBrains\PyCharmCE2021.3\plugins\intellibot.jar", and restart the pycharm. Then "IntelliBot #patched" from Marketplace.**

This steps worked for me. it solved my issue. Thanks
