### ISSUE TITLE
v. 0.6.4 causes IDE fatal errors for IntelliJ12

### ISSUE THREAD

**Issue by schroest** [millennialmedia/intellibot#67]
Since the last update I constantly get many exception which are caused by the intellibot plugin. I tried to reinstall the plugin with no effect.
I am using intelliJ 12 under MacOSx 10.9

I'll get the following exceptions on editing *.robot files
```java
com.intellij.reference.SoftReference.dereference(Ljava/lang/ref/Reference;)Ljava/lang/Object;: com.intellij.reference.SoftReference.dereference(Ljava/lang/ref/Reference;)Ljava/lang/Object;
java.lang.NoSuchMethodError: com.intellij.reference.SoftReference.dereference(Ljava/lang/ref/Reference;)Ljava/lang/Object;
	at com.millennialmedia.intellibot.RobotBundle.getBundle(RobotBundle.java:32)
	at com.millennialmedia.intellibot.RobotBundle.message(RobotBundle.java:27)
	at com.millennialmedia.intellibot.ide.inspections.compilation.RobotKeywordNotFound.getMessage(RobotKeywordNotFound.java:50)
	at com.millennialmedia.intellibot.ide.inspections.SimpleInspectionVisitor.visitElement(SimpleInspectionVisitor.java:31)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:213)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:412)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:370)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.a(LocalInspectionsPass.java:341)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:78)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:309)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:306)
	at com.intellij.concurrency.JobLauncherImpl$2$1.run(JobLauncherImpl.java:115)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
	at com.intellij.concurrency.JobLauncherImpl$2.process(JobLauncherImpl.java:113)
	at com.intellij.concurrency.JobLauncherImpl$1.run(JobLauncherImpl.java:54)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:439)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
	at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
	at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:97)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
```
```java
Error during dispatching of java.awt.event.InvocationEvent[INVOCATION_DEFAULT,runnable=com.apple.eawt._AppEventHandler$_AppEventDispatcher$1@3eec3af5,notifier=null,catchExceptions=false,when=1404983177652] on apple.awt.CToolkit@712cb19: com.intellij.reference.SoftReference.dereference(Ljava/lang/ref/Reference;)Ljava/lang/Object;
java.lang.NoSuchMethodError: com.intellij.reference.SoftReference.dereference(Ljava/lang/ref/Reference;)Ljava/lang/Object;
	at com.millennialmedia.intellibot.RobotBundle.getBundle(RobotBundle.java:32)
	at com.millennialmedia.intellibot.RobotBundle.message(RobotBundle.java:27)
	at com.millennialmedia.intellibot.ide.config.RobotColorsPage.<clinit>(RobotColorsPage.java:60)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.loadClass(ExtensionComponentAdapter.java:148)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentImplementation(ExtensionComponentAdapter.java:63)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getComponentInstance(ExtensionComponentAdapter.java:70)
	at com.intellij.openapi.extensions.impl.ExtensionComponentAdapter.getExtension(ExtensionComponentAdapter.java:111)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.processAdapters(ExtensionPointImpl.java:241)
	at com.intellij.openapi.extensions.impl.ExtensionPointImpl.getExtensions(ExtensionPointImpl.java:185)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:111)
	at com.intellij.openapi.extensions.Extensions.getExtensions(Extensions.java:98)
	at com.intellij.openapi.options.colors.pages.ColorSettingsPagesImpl.getRegisteredPages(ColorSettingsPagesImpl.java:43)
	at com.intellij.application.options.colors.ColorAndFontOptions.a(ColorAndFontOptions.java:513)
	at com.intellij.application.options.colors.ColorAndFontOptions.a(ColorAndFontOptions.java:504)
	at com.intellij.application.options.colors.ColorAndFontOptions.e(ColorAndFontOptions.java:494)
	at com.intellij.application.options.colors.ColorAndFontOptions.buildConfigurables(ColorAndFontOptions.java:318)
	at com.intellij.openapi.options.SearchableConfigurable$Parent$Abstract.getConfigurables(SearchableConfigurable.java:76)
	at com.intellij.openapi.options.newEditor.OptionsTree.a(OptionsTree.java:502)
	at com.intellij.openapi.options.newEditor.OptionsTree.access$500(OptionsTree.java:56)
	at com.intellij.openapi.options.newEditor.OptionsTree$EditorNode.buildChildren(OptionsTree.java:532)
	at com.intellij.openapi.options.newEditor.OptionsTree$EditorNode.buildChildren(OptionsTree.java:519)
	at com.intellij.ui.treeStructure.CachingSimpleNode.getChildren(CachingSimpleNode.java:36)
	at com.intellij.ui.treeStructure.SimpleTreeStructure.getChildElements(SimpleTreeStructure.java:25)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:67)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:82)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.addToCache(FilteringTreeStructure.java:82)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.rebuild(FilteringTreeStructure.java:62)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:54)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeStructure.<init>(FilteringTreeStructure.java:45)
	at com.intellij.ui.treeStructure.filtered.FilteringTreeBuilder.<init>(FilteringTreeBuilder.java:52)
	at com.intellij.openapi.options.newEditor.OptionsTree$MyBuilder.<init>(OptionsTree.java:757)
	at com.intellij.openapi.options.newEditor.OptionsTree.<init>(OptionsTree.java:92)
	at com.intellij.openapi.options.newEditor.OptionsEditor$3.<init>(OptionsEditor.java:144)
	at com.intellij.openapi.options.newEditor.OptionsEditor.<init>(OptionsEditor.java:144)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.createCenterPanel(OptionsEditorDialog.java:89)
	at com.intellij.openapi.ui.DialogWrapper.init(DialogWrapper.java:1116)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.a(OptionsEditorDialog.java:72)
	at com.intellij.openapi.options.newEditor.OptionsEditorDialog.<init>(OptionsEditorDialog.java:57)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.a(ShowSettingsUtilImpl.java:64)
	at com.intellij.ide.actions.ShowSettingsUtilImpl.showSettingsDialog(ShowSettingsUtilImpl.java:51)
	at com.intellij.ide.MacOSApplicationProvider$Worker$1.handlePreferences(MacOSApplicationProvider.java:101)
	at com.apple.eawt._AppEventLegacyHandler$2.dispatchEvent(_AppEventLegacyHandler.java:90)
	at com.apple.eawt._AppEventLegacyHandler.sendEventToEachListenerUntilHandled(_AppEventLegacyHandler.java:168)
	at com.apple.eawt._AppEventLegacyHandler.handlePreferences(_AppEventLegacyHandler.java:88)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:253)
	at com.apple.eawt._AppEventHandler$_PreferencesDispatcher.performUsing(_AppEventHandler.java:244)
	at com.apple.eawt._AppEventHandler$_AppEventDispatcher$1.run(_AppEventHandler.java:489)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:209)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:715)
	at java.awt.EventQueue.access$400(EventQueue.java:82)
	at java.awt.EventQueue$2.run(EventQueue.java:676)
	at java.awt.EventQueue$2.run(EventQueue.java:674)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.AccessControlContext$1.doIntersectionPrivilege(AccessControlContext.java:86)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:685)
	at com.intellij.ide.IdeEventQueue.d(IdeEventQueue.java:700)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:525)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:348)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:296)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:211)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:201)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:196)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:188)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:122)
```

**Comment by mtrubs** [comment]
can you try this plug-in (install from disk) this would be the same artifact that I would upload to jet brains provided it fixes things. 

https://github.com/millennialmedia/intellibot/raw/6cb8c9514990dbfc23982e385b15d3252c1e3e96/intellibot.jar

**Comment by mtrubs** [comment]
#87
