### ISSUE TITLE
Many exceptions in Pycharm

### ISSUE THREAD

**Issue by pchomik** [millennialmedia/intellibot#81]
Pycharm: 4.0.4
Plugin version: 0.6.4

Everyday Pycharm show many notification that plugin raise exception. Could you look what is going on?

```
Already disposed
java.lang.AssertionError: Already disposed
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:281)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:53)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:40)
	at com.intellij.psi.util.PsiModificationTracker$SERVICE.getInstance(PsiModificationTracker.java:57)
	at com.jetbrains.python.psi.types.TypeEvalContextCache.getContext(TypeEvalContextCache.java:65)
	at com.jetbrains.python.psi.types.TypeEvalContext.codeInsightFallback(TypeEvalContext.java:121)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:233)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:893)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:884)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:39)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:37)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:32)
	at com.millennialmedia.intellibot.ide.inspections.compilation.RobotKeywordNotFound.skip(RobotKeywordNotFound.java:42)
	at com.millennialmedia.intellibot.ide.inspections.SimpleInspectionVisitor.visitElement(SimpleInspectionVisitor.java:26)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:213)
	at com.intellij.codeInspection.InspectionEngine.acceptElements(InspectionEngine.java:80)
	at com.intellij.codeInspection.InspectionEngine.createVisitorAndAcceptElements(InspectionEngine.java:69)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.runToolOnElements(LocalInspectionsPass.java:289)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.access$000(LocalInspectionsPass.java:75)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:258)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass$2.process(LocalInspectionsPass.java:255)
	at com.intellij.concurrency.ApplierCompleter.execAndForkSubTasks(ApplierCompleter.java:122)
	at com.intellij.concurrency.ApplierCompleter.access$000(ApplierCompleter.java:44)
	at com.intellij.concurrency.ApplierCompleter$1.run(ApplierCompleter.java:85)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1146)
	at com.intellij.concurrency.ApplierCompleter$2.run(ApplierCompleter.java:94)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:281)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.registerIndicatorAndRun(ProgressManagerImpl.java:278)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:233)
	at com.intellij.concurrency.ApplierCompleter.wrapInReadActionAndIndicator(ApplierCompleter.java:106)
	at com.intellij.concurrency.ApplierCompleter.compute(ApplierCompleter.java:82)
	at jsr166e.CountedCompleter.exec(CountedCompleter.java:684)
	at jsr166e.ForkJoinTask.doExec(ForkJoinTask.java:260)
	at jsr166e.ForkJoinPool$WorkQueue.runTask(ForkJoinPool.java:858)
	at jsr166e.ForkJoinPool.scan(ForkJoinPool.java:1687)
	at jsr166e.ForkJoinPool.runWorker(ForkJoinPool.java:1642)
	at jsr166e.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:109)
```

**Comment by joppa27** [comment]
Also seeing this same error, for the first time today on both Windows & Linux across two different projects.
python: 2.7
pycharm: 4.0.6
Intellibot: 0.6.5

**Comment by mtrubs** [comment]
can you try this plug-in (install from disk) this would be the same artifact that I would upload to jet brains provided it fixes things. 

https://github.com/millennialmedia/intellibot/raw/6cb8c9514990dbfc23982e385b15d3252c1e3e96/intellibot.jar

**Comment by joppa27** [comment]
I wish I had more details for why this happened. The error seems to have gone away for now, strange because when I first uninstalled & re-installed the intellibot plugin, the error was still there.

I have the jar, and will use it instead the next time i see the error.

**Comment by mtrubs** [comment]
#87

**Comment by jcdevil** [comment]
Hi,
Using also get this king of error, using
Python 2.7.9
PyCharm 4.5
Intellibot 0.6.6

Thx for your help :) and if you need more info, let me know !

Already disposed: Project (Disposed) PyForge
java.lang.AssertionError: Already disposed: Project (Disposed) PyForge
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:282)
	at com.intellij.openapi.components.impl.ComponentManagerImpl.getPicoContainer(ComponentManagerImpl.java:54)
	at com.intellij.openapi.components.ServiceManager.getService(ServiceManager.java:37)
	at com.intellij.psi.util.PsiModificationTracker$SERVICE.getInstance(PsiModificationTracker.java:57)
	at com.jetbrains.python.psi.types.TypeEvalContextCache.getContext(TypeEvalContextCache.java:65)
	at com.jetbrains.python.psi.types.TypeEvalContext.codeInsightFallback(TypeEvalContext.java:131)
	at com.jetbrains.python.psi.impl.PyClassImpl.getAncestorClasses(PyClassImpl.java:234)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:908)
	at com.jetbrains.python.psi.impl.PyClassImpl.visitMethods(PyClassImpl.java:899)
	at com.millennialmedia.intellibot.psi.ref.RobotPythonClass.getDefinedKeywords(RobotPythonClass.java:39)
	at com.millennialmedia.intellibot.psi.ref.ResolverUtils.resolveKeywordFromFile(ResolverUtils.java:37)
	at com.millennialmedia.intellibot.psi.ref.RobotKeywordReference.resolve(RobotKeywordReference.java:32)
	at com.millennialmedia.intellibot.ide.inspections.compilation.RobotKeywordNotFound.skip(RobotKeywordNotFound.java:42)
	at com.millennialmedia.intellibot.ide.inspections.SimpleInspectionVisitor.visitElement(SimpleInspectionVisitor.java:26)
	at com.intellij.psi.impl.source.tree.LeafPsiElement.accept(LeafPsiElement.java:213)

**Comment by joppa27** [comment]
after upgrading to intellibot 0.6.6 I haven't seen the error anymore, will post back here if my status changes.
