### ISSUE TITLE
Plugin throws internel error wont work

### ISSUE THREAD

**Issue by pmhalder** [millennialmedia/intellibot#82]
com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0 [Plugin: com.millennialmedia.intellibot]: com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0 [Plugin: com.millennialmedia.intellibot]
com.intellij.diagnostic.PluginException: com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0 [Plugin: com.millennialmedia.intellibot]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:108)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:62)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:141)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:72)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:743)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPassFactory$MyLocalInspectionsPass.getInspectionTools(LocalInspectionsPassFactory.java:84)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:58)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:345)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
	at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
	at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
	at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
	at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.UnsupportedClassVersionError: com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:153)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:149)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:125)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:102)
	... 29 more

com.intellij.diagnostic.PluginException: com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0 [Plugin: com.millennialmedia.intellibot]
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:108)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:63)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
	at java.lang.Class.forName0(Native Method)
	at java.lang.Class.forName(Class.java:249)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.findClass(AbstractExtensionPointBean.java:42)
	at com.intellij.openapi.extensions.AbstractExtensionPointBean.instantiate(AbstractExtensionPointBean.java:62)
	at com.intellij.codeInspection.InspectionEP.instantiateTool(InspectionEP.java:141)
	at com.intellij.codeInspection.ex.InspectionToolWrapper.getTool(InspectionToolWrapper.java:72)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.getInspectionTools(LocalInspectionsPass.java:743)
	at com.intellij.codeInsight.daemon.impl.WholeFileLocalInspectionsPassFactory$3.getInspectionTools(WholeFileLocalInspectionsPassFactory.java:106)
	at com.intellij.codeInsight.daemon.impl.LocalInspectionsPass.collectInformationWithProgress(LocalInspectionsPass.java:136)
	at com.intellij.codeInsight.daemon.impl.ProgressableTextEditorHighlightingPass.doCollectInformation(ProgressableTextEditorHighlightingPass.java:58)
	at com.intellij.codeHighlighting.TextEditorHighlightingPass.collectInformation(TextEditorHighlightingPass.java:62)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1$1.run(PassExecutorService.java:357)
	at com.intellij.openapi.application.impl.ApplicationImpl.tryRunReadAction(ApplicationImpl.java:1182)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass$1.run(PassExecutorService.java:348)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:226)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.doRun(PassExecutorService.java:345)
	at com.intellij.codeInsight.daemon.impl.PassExecutorService$ScheduledPass.run(PassExecutorService.java:321)
	at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:145)
	at com.intellij.concurrency.JobLauncherImpl$3.call(JobLauncherImpl.java:142)
	at java.util.concurrent.FutureTask$Sync.innerRun(FutureTask.java:303)
	at java.util.concurrent.FutureTask.run(FutureTask.java:138)
	at com.intellij.concurrency.PrioritizedFutureTask.access$101(PrioritizedFutureTask.java:31)
	at com.intellij.concurrency.PrioritizedFutureTask$1.run(PrioritizedFutureTask.java:70)
	at com.intellij.concurrency.PrioritizedFutureTask.run(PrioritizedFutureTask.java:113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.runTask(ThreadPoolExecutor.java:895)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:918)
	at java.lang.Thread.run(Thread.java:695)
Caused by: java.lang.UnsupportedClassVersionError: com/millennialmedia/intellibot/ide/inspections/cleanup/RobotImportNotUsed : Unsupported major.minor version 51.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClassCond(ClassLoader.java:637)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:621)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:471)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:153)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:149)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:125)
	at com.intellij.ide.plugins.cl.PluginClassLoader.b(PluginClassLoader.java:102)
	... 29 more

**Comment by orlof** [comment]
I had the same problem with osx. Intellibot is compiled with java version 1.7. Older versions of idea and pycharm are shipped with java version 1.6. I was able to fix the problem by installing Oracle java 1.8 and running pycharm with it.

https://intellij-support.jetbrains.com/entries/23455956-Selecting-the-JDK-version-the-IDE-will-run-under

It would be nice to have intellibot distributions compiled with java 1.6.

**Comment by mtrubs** [comment]
I am not sure I understand why compiling in java 1.7 would break things.  
super annoying.  I forgot I have moved my intellij to use java 1.7 (thanks to apple for deleting 1.6 on upgrade).  I should be able to address this then.

**Comment by orlof** [comment]
I think it breaks for me because I have a bit oldish version of IntelliJ that was shipped to run with jdk 1.6 (osx). The plugin is compiled with java bytecode version 1.7 and my IntelliJ's java 1.6 cannot run those classes and it spits out "Unsupported major.minor version 51.0" exception.

I think it would be fixed if you could set:
File | Settings | Build, Execution, Deployment | Compiler | Java Compiler | Project bytecode version
-> 1.6

**Comment by mtrubs** [comment]
can you try this plug-in (install from disk) this would be the same artifact that I would upload to jet brains provided it fixes things. 

https://github.com/millennialmedia/intellibot/raw/6cb8c9514990dbfc23982e385b15d3252c1e3e96/intellibot.jar

**Comment by mtrubs** [comment]
#87
